### ISSUE TITLE
Rewire doesn't work with Isparta

### ISSUE THREAD

**Issue by renanvalentin** [speedskater/babel-plugin-rewire#105]
Hello guys!

I'm using react-redux-starter-kit and we have this config for karma:
[https://github.com/davezuko/react-redux-starter-kit/blob/master/build/karma.conf.js](https://github.com/davezuko/react-redux-starter-kit/blob/master/build/karma.conf.js)

I tried to add the rewire loader (loader: 'isparta?{ babel: { plugins: ["rewire"] } }') at line 69, but I was unable to make it works.

Any idea?
Thanks!

**Comment by speedskater** [comment]
thanks for reporting the issue. I will have a look at it on the upcoming monday. Hope this is okay for you?

**Comment by renanvalentin** [comment]
Thanks for helping @speedskater !

**Comment by speedskater** [comment]
Hi

@renanvalentin I had a look at your issue and modified our own internal project to generate code coverage reports. For this we used babel-istanbul-loader (https://github.com/deepsweet/babel-istanbul-loader). For this to work you have to restructure your webpack config accordingly. Furthermore for your webpack-test-config to work you have to replace babel-loader with babel-istanbul-loader. 
Besides the configuration of the babel plugins to apply reside in the .babelrc and which configuration is used is controlled by process.env.BABEL_ENV.

Could you please let me know if this works for you?

**Comment by renanvalentin** [comment]
Thank you so much for taking a look, I end up using [inject-loader](https://github.com/plasticine/inject-loader), but I will try your solution to see if it works!

Thanks!

**Comment by jonashartwig** [comment]
for future references:

.babelrc:

```
{
  "presets": ["es2015", "react", "stage-2"],
  "plugins": ["transform-runtime"],
  "env": {
      "development": {
          "plugins": [
              ["react-transform", {
                  "transforms": [{
                      "transform": "react-transform-hmr",
                      "imports": ["react"],
                      "locals": ["module"]
                  }, {
                      "transform": "react-transform-catch-errors",
                      "imports": ["react", "redbox-react"]
                  }]
              }]
          ]
      },
      "production": {
          "plugins": [
              "transform-react-remove-prop-types",
              "transform-react-constant-elements"
          ]
      },
      "test": {
          "plugins": ["rewire"]
      }
  }
}

```

karma conf:

```
loaders: [{
                test: /\.jsx?$/,
                exclude: /node_modules/,
                loader: "isparta"
            }
```

this works together with rewire and babel.

regards
