### ISSUE TITLE
Doesn't work for components inherited from other components

### ISSUE THREAD

**Issue by smashercosmo** [speedskater/babel-plugin-rewire#107]
All my components are inherited from PureComponent (with shouldComponentUpdate lifecycle hook). Adding rewire plugin results in the following error:
```
TypeError: this._GetDependency__ is not a function
```
Error goes away if I extend React.Component directly. I'm using version 0.1.22.

**Comment by smashercosmo** [comment]
I investigated it a bit further and the problem is in using class properties:
```javascript
import shouldComponentUpdate from 'react-pure-render/function';

export default class PureComponent extends React.Component {
  shouldComponentUpdate = shouldComponentUpdate;
}

class SomeComponent extends PureComponent {}
```

when defining PureComponent in this way:
```javascript
import shouldComponentUpdate from 'react-pure-render/function';

export default class PureComponent extends React.Component {
  shouldComponentUpdate(nextProps, nextState) {
     return shouldComponentUpdate(nextProps, nextState);
  }
}
```
error goes away

**Comment by speedskater** [comment]
Could you please try 1.0.0-rc-1 as it is the latest version.

**Comment by smashercosmo** [comment]
Well, actually I can't) Because version 1.0.0 uses babel 6 and we're using babel 5. I can try it on the test project, but if it works, then probably it should be backported to 0.1.23 branch.

**Comment by speedskater** [comment]
I am sorry, but I won't be able to do the backport on the 0.1.22 branch, as there are major differences in the mechanism how the rewiring actually works and it will take too much time to bring the changes to the babel 5 version. 
Maybe if the babel 6 version works you could try to preprocess your files with the babel 6 plugin first.

**Comment by smashercosmo** [comment]
Ok. Got it. I think, I just won't be using class properties in this particular case. That's the easiest fix)

**Comment by speedskater** [comment]
@smashercosmo thank you. and sorry for the inconvenience.

**Comment by smashercosmo** [comment]
@speedskater no worries) and thx for great plugin

**Comment by speedskater** [comment]
@smashercosmo you are welcome
