### ISSUE TITLE
Disable based on environment

### ISSUE THREAD

**Issue by chrisblossom** [speedskater/babel-plugin-rewire#113]
Is it possible to disable based on environment?

Lets say I want to rewire my API calls but I want to test them against a real mocking server during CI, or locally when specified. Is this currently possible?

**Comment by erykpiast** [comment]
You mean something like `env` in `.babelrc`? https://babeljs.io/docs/usage/babelrc/

**Comment by chrisblossom** [comment]
@erykpiast Yes, like that, but would need to be implemented as a config option for the plugin. Otherwise Babel will fail to compile because it won't understand ```.__Rewire__``` and will fail with error messages such as: ```TypeError: _variable2.default.__Rewire__ is not a function```

Similar to how [codemix/babel-plugin-typecheck](https://github.com/codemix/babel-plugin-typecheck#pragmas) has done.

**Comment by speedskater** [comment]
@chrisblossom Thanks for creating the issue. I think I haven't understood your request completly regarding the API and the real mocking server. Could you please explain your example in more detail?

**Comment by chrisblossom** [comment]
I use [getsandbox.com](https://getsandbox.com/) to generate mocked API responses for CI/integration testing and use babel-plugin-rewire for local unit testing. I have been using ```if``` statements for specific environments and was hoping this is/could be a config option instead.

Does that make sense?

**Comment by speedskater** [comment]
@chrisblossom, @erykpiast sorry for the delay, but I were in a big hurry due to a release over the last month. 
Regarding your problem I think I understood your issue but I think I am not really getting how your are writing your tests. Could you please provide a sample code, with how you are currently doing your tests and what your ideal API should look like?
