### ISSUE TITLE
Reset all dependencies

### ISSUE THREAD

**Issue by renke** [speedskater/babel-plugin-rewire#114]
It would be really useful to have a `__ResetAllDependencies__` function that you could just call in a afterEach hook. It's pretty easy to forget to add `__ResetDependency__` for every `__Rewire__`.

Also, it becomes pretty annoying when you deal with Promise-based tests like this:

``` js
afterEach(() => {
  __ResetAllDependencies__();
});

__Rewire__("doSomethingElse", …);
return doSomething().then(result => {
  assert(result === "foo");
});
```

vs.

``` js
__Rewire__("doSomethingElse", …);
return doSomething().then(result => {
  assert(result === "foo");
  __ResetDependency__("doSomethingElse");
}).catch(error => {
  __ResetDependency__("doSomethingElse");
  throw error;
);
```

Thoughts?

**Comment by jmeas** [comment]
Lmk if there's interest in official support. If there is, I'd be up for trying to PR it. If not, I'll prob. make a 3rd party lib to do it (tho' I think it belongs in core).

This feature seems similar to sinon's analogous way to release all stubs when using sandboxes.

**Comment by TheSavior** [comment]
We use https://github.com/wealthfront/privatestate on top of rewire to set and get variables and restore them after tests.

**Comment by speedskater** [comment]
@renke @jmeas, @TheSavior we in our project use a very small wrapper library which does solve this issue for us.
As resetting all existing dependencies is dependening on the test framework i would prefer to move such functionality in a third party library. Furthermore I think creating a global reset hook is currently not trivial, as the rewired dependencies are registered on a per module basis.

What do you think?

**Comment by renke** [comment]
@speedskater what does the wrapper look like?

Also, on a per-module basis is fine for me, if you mean something like:

```js
import {__ResetAllDependencies__} from "./module"
```
That's exactly what I need.

**Comment by jmeas** [comment]
@speedskater , what I'm thinking about would be test-framework independent, if it's possible.

As @renke describes, I'd expect for `rewire` keep a cache of every module that it stubs internally (it may already do that?). Then, I'd like a method that resets everything from that cache. This should be able to be implemented in a manner that's agnostic to any given test framework.

Sinon's `sandbox.restore();` is analogous to this, and it's framework independent.

> Furthermore I think creating a global reset hook is currently not trivial, as the rewired dependencies are registered on a per module basis.

That does add some complexity, but I think the reward is worth the challenge. I'd be up for giving it a try if you change your mind about adding it into this lib.

**Comment by clayne11** [comment]
I would love to see this.

**Comment by TheSavior** [comment]
@jmeas @clayne11, have you looked at https://github.com/wealthfront/privatestate? That is exactly what it does. It uses rewire and keeps a cache of changed modules and enables you to restore all changed modules.

**Comment by dentuzhik** [comment]
The problem with privatestate (as I was able to understand from its docs), is that it requires changes to the source code for writing tests, and the whole purpose of rewire is avoid doing that.

**Comment by speedskater** [comment]
@dentuzhik, @TheSavior, @clayne11, @jmeas, @renke Sorry to all for the delay. But I just created version 1.1.0-alpha (its flag with beta therefore you have to install it explicitly). This version adds a feature to reset all dependencies regardless of the module. To use it call \_\_rewire\_reset\_all\_\_().
Please let me know if this beta version works for you.

**Comment by dentuzhik** [comment]
Thanks a lot @speedskater, will give it a spin shortly

**Comment by jmeas** [comment]
Nice! I'm not sure if i'll be able to try it out for a few weeks, but I appreciate the effort @speedskater :)

**Comment by gajus** [comment]
Has the `__rewire_reset_all__` been removed?

**Comment by jmeas** [comment]
@gajus development is happening on this branch: https://github.com/speedskater/babel-plugin-rewire/tree/version-1.1.0
