### ISSUE TITLE
1.0.0-rc-1       TypeError: _get__(...).not.exist is not a function

### ISSUE THREAD

**Issue by StyMaar** [speedskater/babel-plugin-rewire#115]
The latest version seams to break should.js (https://github.com/shouldjs/should.js)

but only when it comes to use the main object `should` directly.

This fails
```
import should from 'should';
should.not.exist(error);
```

but this works 

```
import should from 'should';
true.should.be.true;
```

**Comment by speedskater** [comment]
@StyMaar thanks for reporting the issue. Could you please create a PR containing a failing usage test?

**Comment by StyMaar** [comment]
I'm trying to reproduce in this repository but I didn't succeed so far.

**Comment by StyMaar** [comment]
I created a new project that reproduce the bug : https://github.com/StyMaar/repro-babel-plugin-rewire/tree/master

**Comment by StyMaar** [comment]
Ok, I figured out where it comes from (in the generated code):
```
function _get__(variableName) {
    return _RewiredData__ === undefined || _RewiredData__[variableName] === undefined ? _get_original__(variableName) : _RewiredData__[variableName];
}
```
Because the `should` library extends `Object.prototype` with a `Object.prototype.should` attribute, then when performing `_get__("should")`, `_RewiredData__["should]` exists, not in `_RewiredData__` itself, but in Object.prototype …

Btw the bug would affect any library whose name in also the name of a property of `Object.prototype`.

To fix this bug, the only this we need to do is to declare `_RewiredData__` as `Object.create(null)` instead of `{}` to avoid having `Object.prototype` in its prototype chain.

**Comment by StyMaar** [comment]
@speedskater I want to create a PR with my fix but I'm facing a issue with tests :

When I change this in Template.js
```
var REWIRED_DATA_IDENTIFIER = {};
```
with this 
```
var REWIRED_DATA_IDENTIFIER = Object.create(null);
```
And update the fixtures accordingly, it breaks the tests because the transpiling now generates 
```
\n
var _RewiredData__ = Object.create(null);\n
\n
```

instead of just 

```
var _RewiredData__ = Object.create(null);\n
```

Any idea of where those `\n` comes from ?

**Comment by StyMaar** [comment]
@speedskater ping

**Comment by speedskater** [comment]
@StyMaar sorry, i am on hollidays will return on monday

**Comment by speedskater** [comment]
@StyMaar sorry for the delay, and thanks for your fix and your patience. I incorporated your test and your suggested fix into the babel-plugin-rewire repo and added you as a contributor.
I was not able to fix the newline problem, but changed the template to contain the newline as well. It is not a very nice solution to the newline issue but I think it should be sufficient for the time beeing.

**Comment by StyMaar** [comment]
Thank you !

**Comment by killmenot** [comment]
Hi @speedskater

I see that
```js
describe('issue115-should-js', function() {
	it('should js should be supported', function() {
		let should = require('should');
		should.exist(true);
		delete Object.prototype.should;
	});
});
```
works, but what's about the following case?
```js
import should from 'should';

describe('issue115-should-import', function() {
	it('should import should be supported', function() {
		should.equal(true, true);
		delete Object.prototype.should;
	});
});
```
I got `TypeError: _get__(...) is not a function`
