### ISSUE TITLE
@connect not getting rewritten dependency

### ISSUE THREAD

**Issue by mmahalwy** [speedskater/babel-plugin-rewire#116]
```
import React, { Component, PropTypes } from 'react';
import { push } from 'react-router-redux';
import { connect } from 'react-redux';

@connect(
  state => ({
    location: state.routing.locationBeforeTransitions
  }),
  { push }
)
```

`push` is not getting rewritten to anything as `@connect` is getting the original and saving it. Any ideas how to get around this?

**Comment by mmahalwy** [comment]
I think it's due to the binding, via a closure: https://github.com/reactjs/redux/blob/master/src/bindActionCreators.js#L1

**Comment by speedskater** [comment]
@mmahalwy. Its not very nice, but you could use an intermediate function for the mapDispatchToProps.

Like this: 

```js
@connect(
  state => ({
    location: state.routing.locationBeforeTransitions
  }),
  () => { push }
)
```

**Comment by speedskater** [comment]
is this a possible solution in your case?

**Comment by mmahalwy** [comment]
@speedskater I could definitely try it and let you know. I will close for now and reopen if it does not work.
