### ISSUE TITLE
Can't set set multiple variables with one __set__ call

### ISSUE THREAD

**Issue by andrestaht** [speedskater/babel-plugin-rewire#121]
With [rewire](https://www.npmjs.com/package/rewire) it is possible to set [multiple dependencies](https://www.npmjs.com/package/rewire#rewiredmodule__set__obj-object-function) with one `__set__` call:
```
myModule.__set__({
    firstDependency: firstDependencyMock,
    secondDependency: secondDependencyMock
});
```
Currently I have to call `__set__` twice to set these dependencies:
```
myModule.__set__("firstDependency", firstDependencyMock);
myModule.__set__("secondDependency", secondDependencyMock);
```

It would be nice to be able to set multiple dependencies like it is possible with [rewire](https://www.npmjs.com/package/rewire).

**Comment by speedskater** [comment]
@andrestaht I think this is currently impossible. Could you please create a PR with a failing test and I will try to tackle your issue ASAP (but it will take at least another week, till I get to it).

**Comment by speedskater** [comment]
Thanks @andrestaht @nene for providing a test and fixing this issue.
