### ISSUE TITLE
Question: Can I rewire a nested dependency?

### ISSUE THREAD

**Issue by gavriguy** [speedskater/babel-plugin-rewire#122]
Lets Say **moduleA** requires **moduleB**
and **moduleB** requires **moduleC**

Now lets say **moduleC** has an ajax call I want to rewire for testing **moduleA**. Is the a simple way to rewire **moduleC** directly without mocking all dependencies all way down?

**Comment by speedskater** [comment]
@gavriguy Theoretically you can import the Rewire API of moduleB in your test, but I would not recommend to go down this path.
I would just mock moduleB as moduleA depends only on moduleB and that moduleB uses moduleC is an implementation detail of moduleB.

**Comment by gavriguy** [comment]
Thank you for your answer

**Comment by MartinDawson** [comment]
@speedskater That would be an ideal solution however this isn't possible with React when ModuleB uses refs because if you mock ModuleB out then you don't have access to the refs anymore.

I had to go with mocking out the nested dependency.
