### ISSUE TITLE
Isparta + webpack documentation is not correct

### ISSUE THREAD

**Issue by olabalboa** [speedskater/babel-plugin-rewire#126]
The documation about how to use babel-plugin-rewire together with isparta and webpack is not correct. isparta-loader does not handle query parameters.

According to the docs in https://github.com/deepsweet/isparta-loader, babel options can be set in karma.conf.js. To use babel-plugin-rewire, the config should be

```javascript
webpack: {
  isparta: {
    embedSource: true,
    noAutoWrap: true,
    babel: {
      plugins: 'rewire'
    }
  },

```

instead of using query parameters 

```javascript
loader: 'isparta?{ babel: { plugins: ["rewire"] } }'
```

**Comment by speedskater** [comment]
@olabalboa Thanks for providing the hint. I updated the description about how to use isparta. Is this what you intended?
