### ISSUE TITLE
Error: The (rewire) Babel 5 plugin is being run with Babel 6.

### ISSUE THREAD

**Issue by MoonTahoe** [speedskater/babel-plugin-rewire#127]
I am having problems setting up the babel-plugin-rewire.  I installed it and modified my __.babelrc__ to list rewire as a plugin

```javascript
  {
    "presets": [
      "es2015",
      "stage-0",
      "react"
    ],
    "plugins": ["rewire"]
  }
```

When I run webpack or the tests I get an error:

#### Error: The (rewire) Babel 5 plugin is being run with Babel 6

**Comment by MoonTahoe** [comment]
also: `"plubins": ["babel-plugin-rewire"]` causes the same error...

**Comment by TheSavior** [comment]
Try using `1.0.0-rc-2` for babel support. The released stable version only supports babel 5.

**Comment by MoonTahoe** [comment]
Yes that worked...

` $ npm install babel-plugin-rewire@1.0.0-rc-2  --save-dev`    

works!

**Comment by speedskater** [comment]
@MoonTahoe As this works for you. I will close this issue.

**Comment by natalzia-paperless** [comment]
Do we have any timeline on when this change will make it into the next stable release?
