### ISSUE TITLE
Interop with other plugins that rename/replace variables (specifically lodash)

### ISSUE THREAD

**Issue by kentcdodds** [speedskater/babel-plugin-rewire#128]
I use [babel-plugin-lodash](https://npmjs.com/package/babel-plugin-lodash) which changes variable names and moves some things around. Basically, the lodash plugin will change the import statements and usages, but rewire doesn't see this for some reason and uses the original variables. This results in `undefined` errors.

I've created a totally isolated reproducing example repo here: https://github.com/kentcdodds/rewire-lodash-bug (complete with tests and [a travis build](https://travis-ci.org/kentcdodds/rewire-lodash-bug) to know when a PR fixes it).

I'd appreciate it if someone could give the project a look and tell me if I can work around the issue or if there's some way for me to contribute to either project to make this work. My guess is that the change required will be here in rewire, which is why I'm filing the issue here, but just in case, I'll cc @jdalton and @megawac

Thanks!

**Comment by TheSavior** [comment]
This PR might solve your problem: https://github.com/speedskater/babel-plugin-rewire/pull/120

**Comment by kentcdodds** [comment]
Absolutely it will!

**Comment by speedskater** [comment]
@kentcdodds I think this issue should be solved. If not don't hesitate to reopen this issue.
