### ISSUE TITLE
Is it possible to rewire a module's dependencies before their initial evaluation?

### ISSUE THREAD

**Issue by stuartsan** [speedskater/babel-plugin-rewire#129]
Let's say I have module A under test:

```javascript
// module A
import B from './module-b';
export default {};
```
Is it possible in a test of module A to rewire its dependency B, before B's initial evaluation? I.e., if B contains:

```javascript
// module B
console.log('hi from B!');
export default {}
```

Then `hi from B!` is never logged. So far I've been unable to achieve this with `babel-plugin-rewire` and I'm wondering if it is possible. The reason I want to do this is that a third-party library I'm requiring does some stuff upon evaluation that I want to prevent from happening in my test.

**Comment by speedskater** [comment]
@stuartsan I am sorry, but imho this is not possible. As dependencies in es6 are statically analyzed, module B is executed exactly once regardless how many times it is required. The mocking mechanism used by babel-plugin-rewire only changes the value assigned to B in module A not the loading of the module itself. If you want to conditionally load a module you either have to change the dependency to a dynamic one or in case of unit tests, completly mock the module itself. Does this answer help you?

**Comment by stuartsan** [comment]
Makes sense, thanks @speedskater !

**Comment by dentuzhik** [comment]
Would be great, if this case is described in Readme, spend quite some time digging into this issue.

**Comment by stuartsan** [comment]
In case it comes in handy for anyone else in the future: https://github.com/teod/babel-plugin-mock-imports provides an easy to mock a module before it's executed.
