### ISSUE TITLE
Support rewire of private variables

### ISSUE THREAD

**Issue by malonecj** [speedskater/babel-plugin-rewire#13]
rewire-webpack allows you to leak private variables and override variables within a module, not just the external module dependencies. This can be often useful for testing.

Is this something that might be possible in babel-plugin-rewire?

**Comment by girvo** [comment]
:+1: I'd love this

**Comment by speedskater** [comment]
I will have a look into this (will take till the weekend till I have time) but I would restrict it to top level variables.

**Comment by speedskater** [comment]
Thanks @peet for fixing this issue.
