### ISSUE TITLE
Webpack/Karma tests: Uncaught TypeError: Cannot assign to read only property '__get__' of object '#<Object>'

### ISSUE THREAD

**Issue by Janekk** [speedskater/babel-plugin-rewire#133]
I'm getting this even if no actual Rewire API was used in my test code.

Here's the piece of auto-generated code from `tests.webpack.js` where the error occurs

```
	if ((_get__2("_typeOfOriginalExport") === 'object' || _get__2("_typeOfOriginalExport") === 'function') && Object.isExtensible(_get__2("userSession"))) {
	  _get__2("addNonEnumerableProperty")('__get__', _get__2("_get__"));
	  _get__2("addNonEnumerableProperty")('__GetDependency__', _get__2("_get__"));
	  _get__2("addNonEnumerableProperty")('__Rewire__', _get__2("_set__"));
	  _get__2("addNonEnumerableProperty")('__set__', _get__2("_set__"));
	  _get__2("addNonEnumerableProperty")('__reset__', _get__2("_reset__"));
	  _get__2("addNonEnumerableProperty")('__ResetDependency__', _get__2("_reset__"));
	  _get__2("addNonEnumerableProperty")('__with__', _get__2("_with__"));
	  _get__2("addNonEnumerableProperty")('__RewireAPI__', _get__2("_RewireAPI__"));
	}

	exports.__get__ = _get__2("_get__"); // <-- !!! here the error is thrown
	exports.__GetDependency__ = _get__2("_get__");
	exports.__Rewire__ = _get__2("_set__");
	exports.__set__ = _get__2("_set__");
	exports.__ResetDependency__ = _get__2("_reset__");
	exports.__RewireAPI__ = _get__2("_RewireAPI__");
	var _RewiredData__2 = {};
	var _RewireAPI__2 = {};
```

ERROR: `Uncaught TypeError: Cannot assign to read only property '__get__' of object '#<Object>'`

Here are my babel-related dependencies:

```
    "babel-core": "^6.9.0",
    "babel-loader": "^6.2.4",
    "babel-plugin-rewire": "^1.0.0-rc-3",
    "babel-polyfill": "^6.9.0",
    "babel-preset-es2015": "^6.9.0",
    "babel-preset-react": "^6.5.0",
    "babel-preset-stage-0": "^6.5.0",
```

Did anyone have a similar problem?

**Comment by Janekk** [comment]
Hmm, turned out the problem was caused by some specific ES6 syntax used that apparently didn't play well with that object enhancement that `babel-plugin-rewire` is doing. It required some refactoring of some of the ES6 modules involved in order to get rid of that error. Here's the list of things that were causing glitches with `babel-plugin-rewire` in my code (might help someone):

1. Using a `const` object that is exported from a module, for instance I had to change this:

```
    const options = ...
    ....
    export default configOptions;
```

into: 

```
    export default { 
     //former const object
    }
```

2. instead of exporting a singleton object created from a class I converted it into a class with static methods and exported that class

3. Using `module.exports = <obj>` instead of `export default <obj>`

**Comment by anzorb** [comment]
+1 Same issue, works fine with module.exports but fails with ES6 export.

For me, this only happens with isparta instrumenter. Workaround is to either disable code coverage or to use module.exports and not ES6 👎 

Code is here: https://github.com/anzorb/es6-webpack-starter-kit

Change module.exports to export default at the bottom of the file to reproduce.
https://github.com/anzorb/es6-webpack-starter-kit/blob/master/src/Bar.js
command: npm run karma:ci

```
webpack: {
            cache: true,
            devtool: 'inline-source-map',
            debug: true,
            module: {
                preLoaders: [{
                     test: /\.js$/,
                     exclude: /(spec|third-party|node_modules|test)/,
                     loader: 'isparta',
                     query: {
                         babel: {
                             plugins: ['rewire']
                         }
                     }
                 }],
                loaders: [{
                    test: /\.js$/,
                    exclude: /(bower_components|node_modules)/,
                    loader: 'babel',
                    query: {
                        plugins: ['rewire']
                    }
                }]
            },
            node: {
                fs: 'empty'
            }
        },
```

**Comment by speedskater** [comment]
@Janekk it took a bit longer till I got back to this issue, but I created a test for your example, and I think it works now. Could you please let me know if this is indeed the case.

The sample can be found at https://github.com/speedskater/babel-plugin-rewire/tree/master/samples/issue133

**Comment by yvele** [comment]
@speedskater @Janekk  Should this issue be re-opened?  I get the exact same error with `1.0.0-rc-7`

```none
/Users/Me/repo/lib/foo.js:242
exports.__get__ = _get__2("_get__");
                ^

TypeError: Cannot assign to read only property '__get__' of object '#<Object>'
```

**Comment by speedskater** [comment]
@Janekk could you please open a new issue with a minimal sample reproducing your error?

**Comment by yvele** [comment]
@Janekk  I opened a new issue https://github.com/speedskater/babel-plugin-rewire/issues/163 with a minimal sample
