### ISSUE TITLE
__set__ does not apply on variables present on right of an assignment expression

### ISSUE THREAD

**Issue by AdityaHegde** [speedskater/babel-plugin-rewire#136]
```javascript
var varA, varB, varC;

function setVarA(bool) {
  if(bool) {
    varA = varB;
  }
  else {
    varA = varC;
  }
}

function setVarB(v) {
  varB = v;
}

function setVarC(v) {
  varC = v;
}

export {
  varA,
  setVarA,
  setVarB,
  setVarC
}
```

get converted to 

```
...
var varA, varB, varC;

function setVarA(bool) {
  if (bool) {
    _assign__("varA", varB);
  } else {
    _assign__("varA", varC);
  }
}

function setVarB(v) {
  _assign__("varB", v);
}

function setVarC(v) {
  _assign__("varC", v);
}
...
```

So testing setVarA is not possible by using ```__set__``` on varB and varC.

Here are my babel versions
"babel-cli": "^6.9.0",
"babel-core": "^6.9.1",
"babel-plugin-rewire": "^1.0.0-rc-3",
"babel-preset-es2015": "^6.9.0",
"babel-register": "^6.9.0",
"babel-template": "^6.9.0",
"babel-types": "^6.9.1",

A few things i found after moving around code,

```
var varA, varB;

function setVarA(..) {
  //not defined locally
  vraA  = varB;

  //as function parameter
  varA = someFunction(varB);
}
```
is being converted to
```
...
var varA, varB;

function setVarA(..) {
  //not defined locally
  vraA  = _get__("varB");

   //as function parameter
  _assign__("varA", _get__("someFunction")(_get__("varB")));
}
...
```

**Comment by speedskater** [comment]
@AdityaHegde Sorry for the long long delay. But I have just verified that this issue is already resolved. Furthermore there are now two test covering your issue (https://github.com/speedskater/babel-plugin-rewire/tree/master/fixtures/transformation/issue136, https://github.com/speedskater/babel-plugin-rewire/tree/master/samples/issue136)
