### ISSUE TITLE
Mock 'require' not possible

### ISSUE THREAD

**Issue by hoschi** [speedskater/babel-plugin-rewire#139]
I can't mock `require` to mock `require.ensure` (webpack stuff). I got the following error:
```
"_get__(...).__set__ is not a function"
```

Code under test:
```
export default {
    path: 'mail',
    getComponent(nextState, next) {
        require.ensure([], (require) => {
            next(null, require('./MailFeature').default);
        }, 'feature-mail');
    }
};
```

My current workaround is:
```
import rewire from 'rewire';
import path from 'path';

export function mockRequireEnsure (moduleFileName, dir) {
    const absoluteModuleFileName = path.resolve(dir, moduleFileName);
    const Module = rewire( absoluteModuleFileName );
    const scopedRequire = (possibleRelativeFileName) => require(path.resolve(dir, possibleRelativeFileName));

    const resetRewire = Module.__set__('require', {
        ensure(preModules, callback) {
            callback(scopedRequire);
        }
    });

    return {
        resetRewire,
        Module
    };
}
```

**Comment by dtothefp** [comment]
same problem here, I tried using the `__RewireAPI__` but didn't work, I'm doing something like this now

```js
import rewire from 'rewire';

describe('#gatherCommonjsModules', () => {
  const gatherMod = rewire('../src/utils/gather-commonjs-modules');
  const oldRequire = gatherMod .__get__('require');
  const {default: gather} = gatherMod;

  before(() => {
    const mock = (fp) => require(fp);

    mock.resolve = (fp) => fp;
    gatherMod.__set__('require', mock);
  });

  after(() => {
    gatherMod.__set__('require', oldRequire)
  });
});
```

**Comment by speedskater** [comment]
@hoschi, @dtothefp I think your problem is that you are trying to mock a global variable, which is not supported by babel-plugin-rewire.
Could you try to get around this by definining a temporary variable containing the ensure variable.
let ensureModule = require.ensure.
This should allow you to rewire the variable ensureModule.
Does this work for you?

**Comment by hoschi** [comment]
I switched away from this plugin, because I use AVA for testing which compiles the files very often and the rewireing all modules was too much for my use case.

**Comment by speedskater** [comment]
@hoschi sorry to hear this. Maybe we can improve the rewiring performance some day in the future.

**Comment by hoschi** [comment]
Perhaps it would make sense to whitelist modules which should be rewired. I have 230 tests and 225 files, but would really need rewire in two or three tests. If this is something you are interessted in, feel free to CC me in the issue ;)

**Comment by speedskater** [comment]
@hoschi. Maybe it helps using different profiles. In the codebase we are working on we have different babel profiles for developing and testing (with and without this plugin enabled). Furthermore we use webpack in combination with karma and I think we only rewire our own source code. Although the initial start up time is a bit long the incremental test builds are okay.
