### ISSUE TITLE
__set__ doesn't return revert function with objects

### ISSUE THREAD

**Issue by patapizza** [speedskater/babel-plugin-rewire#146]
When calling __set__ with an object, the returned value is not a function.

Expected: https://github.com/jhnns/rewire#rewiredmodule__set__obj-object-function
Got: TypeError: revert is not a function

**Comment by speedskater** [comment]
@patapizza Thanks for pointing this out. We will have a look at it.

**Comment by speedskater** [comment]
@patapizza Sorry again for this delay, but I was tackling a serious issue with jsx support. I hope I can come back to your issue ASAP.

**Comment by speedskater** [comment]
@patapizza I just implemented the revert function feature, as used by rewire.js. It will be in the upcoming rc-7 which will be released today.

**Comment by patapizza** [comment]
Cool, thanks!
