### ISSUE TITLE
Renaming of Child Component

### ISSUE THREAD

**Issue by mtthomas** [speedskater/babel-plugin-rewire#147]
Child components are rendered as Component and not as their component name.
```
<Foo>
 <Bar />
</Foo>
```
is rendered as 
```
<Foo>
 <Component />
</Foo>
```

This makes it difficult to find components by their name in Enzyme.

**Comment by speedskater** [comment]
@mtthomas thanks for providing this issue. I think it should be fixed in the new version 1.0.0-rc5. Hence, I will close this issue. If this does not solve your problem, please do not hestitate to reopen it.
