### ISSUE TITLE
RC5 broke our mocha-electron test suite

### ISSUE THREAD

**Issue by lparry** [speedskater/babel-plugin-rewire#150]
first file that tries to load errors out with:

```
Error encountered in node_modules/babel-core/lib/transformation/file/index.js: Uncaught TypeError: /filepath/aFileStartingWithA.js: Property id of VariableDeclarator expected node to be of a type ["LVal"] but instead got "CallExpression"
```

going back to RC4 the problem goes away. Not sure what kind of info I can provide that would be useful, the error is a bit cryptic to me

.babelrc for tests looks like:

```json
{
  "presets": ["es2015", "stage-0", "react"],
  "plugins": [
  "transform-decorators-legacy",
      "rewire",
      ["babel-plugin-module-alias", [
      { "src": "./some/aliasec/paths", "expose": "test" },
      ...
      ]]
    ]
  }  
}
```

**Comment by chrisblossom** [comment]
I am seeing this same issue but only with one of my test runners ([Wallabyjs](https://wallabyjs.com/)).

**Comment by speedskater** [comment]
@lparry thanks for reporting the issue can you please provide a small sample PR ?

**Comment by speedskater** [comment]
@lparry, @chrisblossom I think rc6 should fix this issue. Could you please try it and let me know if it works for you?

**Comment by davidpadbury** [comment]
@speedskater had a similar issue and just tried rc6. Looks resolved. Thanks!

**Comment by speedskater** [comment]
@davidpadbury thanks for the fast feedback.

**Comment by lparry** [comment]
@speedskater sorry I couldn't get back to you with a PR, RC6 did fix it for us, thanks!

**Comment by chrisblossom** [comment]
@speedskater it fixed it for me too. Thank you!!
