### ISSUE TITLE
1.0 release?

### ISSUE THREAD

**Issue by mik01aj** [speedskater/babel-plugin-rewire#151]
First beta of 1.0 came in Nov 26, 2015. 10 months later, could we get an official 1.0? Or is there any important issue that should be fixed before 1.0?

FWIW, I was using `1.0.0-rc3` for quite some time without noticing any problems.

My project is approaching production and at this point it's not comforting to see some beta or rc version in `package.json`. Maybe it's just me, but I think it's time for 1.0!  🎉

**Comment by speedskater** [comment]
@mik01aj thanks for your feedback. As i have created some regressions in rc5 which required another rc6 ;) I will wait another 10 tens. If no showstopper occurs till then I will pump the version to 1.0.0

**Comment by jmeas** [comment]
Thanks for the update, @speedskater !

> I will wait another 10 tens.

10 tens ❓

**Comment by speedskater** [comment]
@jmeas ten days ;) . As we had a compatibility issue with rewire.js regarding the __set__ operation (please see issue #146. I will have to wait again, whether this will result in another regression. But we are coming closer to 1.0 :).

**Comment by Coobaha** [comment]
@speedskater rc7 fails for me with
```
/* @flow */

export type Separators = {
    decimalSeparator?: string,
    thousandsSeparator?: string,
}

export type L10N = {
    separators: Separators
}

const defaultSeparators: Separators = {
    decimalSeparator: '',
    thousandsSeparator: ''
};

let separators: Separators = { ...defaultSeparators };

const l10n: L10N = {
    get separators(): Separators {
        return { ...separators };
    },
    set separators(data: Separators): void {
        separators = {
            ...defaultSeparators,
            ...separators,
            ...data
        };
    }
};

export default l10n;
```

```
/l10n.js: Property key of ObjectMethod expected node to be of a type ["Identifier","StringLiteral","NumericLiteral"] but instead got "CallExpression"
```

**Comment by speedskater** [comment]
@Coobaha thanks for providing the issue description. It is fixed and will be included in the next version. For future issue it would be great if you could create separate issues.

**Comment by speedskater** [comment]
It took quite a long time. But i just pumped version number to 1.0.0. Any further issues will be resolved according to semver versioning. Sorry for all the inconvenience.

**Comment by jmeas** [comment]
Thanks @speedskater ! This is great to hear :)
