### ISSUE TITLE
Dev environment

### ISSUE THREAD

**Issue by w0nche0l** [speedskater/babel-plugin-rewire#153]
Can you specify somewhere that should be only enabled for your test environments in your .babelrc? It creates a very difficult to track down error in the react native packager.

**Comment by rainydio** [comment]
https://babeljs.io/docs/usage/babelrc/ env option

**Comment by speedskater** [comment]
@rainydio thanks for providing an answer.
@w0nche0l Does the answer of @rainydio did solve your issue?
