### ISSUE TITLE
Error when exported function contains other functions.

### ISSUE THREAD

**Issue by jseminck** [speedskater/babel-plugin-rewire#155]
Hello,

babel-rewire-plugin mocking fails when the exported function contains another function definition. I will create a PR with a failing test case to investigate, but basically, when trying to mock out the variable `test` using the syntax `fileName.__set__({test: 2000});` for the following file, this error is returned:

Error
**TypeError: _get__(...).__set__ is not a function**

File:
```js
const test = 0

export default function getTestValue() {
  return addOne(test);

  function addOne(value) {
    return value + 1;
  }
}
```

However, the following approaches work:

```js
const test = 0

export default function getTestValue() {
  const addOne = function(value) {
    return value + 1;
  }

  return addOne(test);
}
```

And

```js
const test = 0

export default function getTestValue() {
    return addOne(test);
}

function addOne(value) {
  return value + 1;
}
```

Cheers,

**Comment by speedskater** [comment]
@jseminck thanks for opening this issue together with the PR describing the problem. It should be fixed in rc6. Could you please let me know if it works for you.

**Comment by jseminck** [comment]
Hi. Thanks for the fast reply. Indeed this seems to work now, but we cannot upgrade due to compatibility issue with `babel-plugin-rewire', see issue https://github.com/speedskater/babel-plugin-rewire/issues/148
