### ISSUE TITLE
Should RC (release candidate) version be published to NPM with a specific tag?

### ISSUE THREAD

**Issue by yvele** [speedskater/babel-plugin-rewire#160]
The **latest** `babel-plugin-rewire` is a **RC** version : `1.0.0-rc-7`.

Release candidates (and beta) versions should be published to NPM with a specific [tag](https://docs.npmjs.com/cli/dist-tag) : prerelease for example. Wich makes `npm install` only install the `latest`stable release.

https://docs.npmjs.com/cli/dist-tag
https://docs.npmjs.com/cli/version

----

By the way, `0.1.22` is the latest stable release, right? `1.0.0-rc-7` is not working, I have an error that looks like https://github.com/speedskater/babel-plugin-rewire/issues/133

**Comment by speedskater** [comment]
@yvele you are right this is not correct version schema. And i will switch to semantic versioning ASAP, but I cannot give you a timeline. The 0.1.22 is only stable if you consider babel 5. In case of babel 6 use rc-7. Regarding your issue, Please create a minimal sample reproducing your issue and open a new issue.

**Comment by speedskater** [comment]
It took quite a long time. But i just pumped version number to 1.0.0. Any further issues will be resolved according to semver versioning. And beta versions will be tagged with prereleases in the future.

**Comment by yvele** [comment]
@speedskater Good news!

**Comment by yvele** [comment]
By the way @speedskater I think you should also make a Github releases (git tags) for each new.. release.

The Github release page can be used as a changelog (you can add md release notes)

https://github.com/speedskater/babel-plugin-rewire/releases
