### ISSUE TITLE
Rewire Parent Class

### ISSUE THREAD

**Issue by dtothefp** [speedskater/babel-plugin-rewire#161]
Doesn't seem possible to do:

```js
import Parent from './some-parent'

export default class Child extends Parent {}
```

then rewire 
```js
import Child from './child'

Child.__Rewire__('Parent', class {
   constructor(arg) {
      //thought this would be invoked but isn't ¯\_(ツ)_/¯
   }
})

const child = new Child()
```

Am I missing something or is this just not a use case for Rewire?

**Comment by speedskater** [comment]
@dtothefp Sorry for the late reply. Unfortunately this is not a case for babel-plugin-rewire.

The reason is that Parent is already bound to the imported class when Child is declared. If you want to rewire the superclass you have to export a factory function.
