### ISSUE TITLE
Err: 'rewire' is resolving to different Babel version

### ISSUE THREAD

**Issue by maxkolyanov** [speedskater/babel-plugin-rewire#17]
Getting an error when performing simple rewire inside of karma test
`TypeError: Plugin "rewire" is resolving to a different Babel version than what is performing the transformation.`

The list for babel-core looks as follows, they all seem to use 5.7.4, confused how could it possibly in any way resolve to different versions of babel
```
├─┬ babel@5.6.23
│ └── babel-core@5.7.4 
├── babel-core@5.7.4 
├─┬ babel-eslint@3.1.23
│ └── babel-core@5.7.4 
├─┬ babelify@6.1.3
│ └── babel-core@5.7.4 
└─┬ gulp-babel@5.1.0
  └── babel-core@5.7.4 
```

**Comment by speedskater** [comment]
Could you please update babel and babel-plugin-rewire to the latest versions for your project. Remove the node_modules folder and call again npm install.

Does this resolve your issue?
