### ISSUE TITLE
Version 1.1 breaks usage with Mocha

### ISSUE THREAD

**Issue by fix-fix** [speedskater/babel-plugin-rewire#190]
After updating babel-plugin-rewire to 1.1.0 from 1.0.0 Mocha throws an error after executing `mocha.checkLeaks()`, which prevents any tests from running:
`Error: global leak detected: __$$GLOBAL_REWIRE_NEXT_MODULE_ID__`

Also why 1.1.0 is still not in the `master` branch, when it's published as `latest` tag on npm? It's confusing.

**Comment by tdebarochez** [comment]
The problem seems to be here: https://github.com/speedskater/babel-plugin-rewire/compare/version-1.1.0#diff-dc8b7ed135377c8e7840221454caa130R73

**Comment by gruckus-gruckus** [comment]
This still seems to be an issue in 1.2.0. Not sure why closed
