### ISSUE TITLE
TypeError: _get__(...).__GetDependency__ is not a function

### ISSUE THREAD

**Issue by perrin4869** [speedskater/babel-plugin-rewire#194]
I'm trying to migrate from `rewire` to `babel-plugin-rewire` in my gulp plugin, `gulp-i18next-conv`, but I can't get it to work. I'm getting the error: `TypeError: _get__(...).__GetDependency__ is not a function`

Here is the source code:
https://github.com/perrin4869/gulp-i18next-conv/tree/babel-plugin-rewire

And here is the build log with the error:
https://travis-ci.org/perrin4869/gulp-i18next-conv/jobs/245236074

Any chance you can help me fix the error?
Thanks!

**Comment by GabrSaac** [comment]
Same issue here. Raised a stackoverflow too: https://stackoverflow.com/questions/45305948/cannot-setup-babel-plugin-rewire-for-react-tests

**Comment by perrin4869** [comment]
any chance you can take a look at my code and find a solution? lol
I'll take another look at this soon
