### ISSUE TITLE
__$Resetters__[name] is not a function

### ISSUE THREAD

**Issue by vnovick** [speedskater/babel-plugin-rewire#20]
When exporting an object as in example below:

```javascript
import { node } from 'utils/dom';
import React from 'react';
import Card from 'components/card.component';

class WelcomePanel extends Card {
  constructor(props){
    super(props);
  }

  render() {
    return (
      <div className="welcome-panel">
         <Card content={node.toString()} />
      </div>
      )
  }

  initPanel(el,content){
    React.render( <WelcomePanel content={content} />, el);   
  }
}

export default { WelcomePanel}
```

and importing it through destructuring:

```javascript
import { assert } from 'chai';
import React, { Component } from 'react';
import { WelcomePanel as ComponentToTest } from 'modules/welcomePanel/welcomePanel.component';
'use strict'

describe('Tests General Configuration', function(){


  it('should not be null', function(){

    ComponentToTest.__Rewire__('node',"hey I'm mock")

    let panel = new ComponentToTest
    panel.initPanel(document.body,`This is message no `)
    assert.isNotNull("Basic Test")
  })
})

ComponentToTest.__ResetDependency__('node');

```

I get the following error:

Uncaught TypeError: __$Resetters__[name] is not a function
The same for  __$Setters__[name]

**Comment by speedskater** [comment]
Maybe I have misunderstood you but I think you have an error in your export/import.

Either you should do default export which works as follows:

in WelcomePanel:

export default WelcomePanel;

in the test:

import ComponentToTest  from './src/WelcomePanel';

Or you should used named exports in which case you should do:

in WelcomePanel
export class WelcomePanel ....

int the test:

import { WelcomePanel as ComponentToTest, __Rewire__, __ResetDependency__ }  .....

Or leave WelcomePanel as is and change the test code to:

import { assert } from 'chai';
import React, { Component } from 'react';
import { default as ComponentToTest } from 'modules/welcomePanel/welcomePanel.component';
'use strict'

describe('Tests General Configuration', function(){


  it('should not be null', function(){

    ComponentToTest.__Rewire__('node',"hey I'm mock")

    let panel = new ComponentToTest.WelcomePanel();
    panel.initPanel(document.body,`This is message no `);
    assert.isNotNull("Basic Test");

    //after test code otherwise it will not be called:
   ComponentToTest.__ResetDependency__('node');
  })
})

**Comment by speedskater** [comment]
@vnovick Does the previous comment solve your issue?

**Comment by vnovick** [comment]
The following helped. Thanks:

Welcome panel
```javascript
import { node } from 'utils/dom';
import React from 'react';
import Card from 'components/card.component';

class WelcomePanel extends Card {
  constructor(props){
    super(props);
  }

  render() {
    return (
      <div className="welcome-panel">
         <Card content={node.toString()} />
      </div>
      )
  }

  initPanel(el,content){
    React.render( <WelcomePanel content={content} />, el);   
  }
}

export default { Class: WelcomePanel }
```

Test:

```javascript
import { assert } from 'chai';
import React, { Component } from 'react';
import {Class as ComponentToTest, __Rewire__, __ResetDependency__ } from 'modules/welcomePanel/welcomePanel.component';
'use strict'

describe('Tests General Configuration', function(){


  it('should not be null', function(){

    __Rewire__('node',"hey I'm mock")

    let a = ['a','b','c'];
    for( let b of a){
      
    }

    let panel = new ComponentToTest
    panel.initPanel(document.body,`This is message no `)
    assert.isNotNull("Basic Test")
  })
})

__ResetDependency__('Card');

```
