### ISSUE TITLE
Plugin breaks exporting of objects (karma/webpack)

### ISSUE THREAD

**Issue by PerlPong** [speedskater/babel-plugin-rewire#29]
First, thanks for your work on this plugin.

I have the following issue when try to export an object:

```javascript
// config.js
export let config = { mode: 'development' };

// other_module.js
import { config } from './config.js';
console.log(config.mode);
```

The test bundle compiles ok, but upon execution in the browser it dies with the following error:

````Uncaught TypeError: Cannot read property 'mode' of undefined````

```javascript
// webpack config
module: {
    loaders: [
        {
            test: /\.jsx?$/,
            include: path.resolve(__dirname, 'js'),
            loader: 'babel-loader',
            query: {
                cacheDirectory: '/tmp',
                plugins: ['babel-plugin-rewire']
            }
        },
    ]
},
```

I am using lastest webpack and babel. If I disable the plugin everything is ok. I looked through the transpiled code and I couldn't see anything wrong. Any ideas what could be causing this, or how I can debug?

**Comment by speedskater** [comment]
Thanks for reporting the bug. Could you please create a PR with a usage sample which result in this error?

**Comment by speedskater** [comment]
A test trying to reproduce this error is in the repository https://github.com/speedskater/babel-plugin-rewire/blob/master/samples/issue29/sample.js. Unfortunately the error cannot be reproduced. Could you please provide more details how to reproduce your error?

**Comment by PerlPong** [comment]
I have been debugging this for hours and I am finding it hard to reduce down to a simple test case. I think the problem may be that the plugin is not compatible with the way I have designed my app, rather than a bug, but I would really appreciate your thoughts.

I have a module, config.js, that exports an object like this:

```javascript
// config.js
export let config = { mode: null };
```

And other modules import the config object like this:

```javascript
// other_module.js
import { config } from './config.js';
```

In my tests, I have a root hook that runs before every test and sets some default config settings like this:

```javascript
// test/mocha_root_hooks.js
import { config } from '../config.js';
beforeEach(function() {
    config.mode = 'development';
});
```

This used to work fine, but with your plugin enabled, the tests throw an exception indicating that deeper within the app the config object is undefined. However, when I log the object to the console at the beginning of a test, like below, the config object is defined and populated.

```javascript
describe('something', function() {
    beforeEach(function() {
        console.log(config.mode); // 'development'
        user = makeTestUser(); // dies: TypeError: Cannot read property 'mode' of undefined
    });
    ....
```

So it seems that the tests contain the correct object, initialized by the root hook, but the modules in my app are using an undefined identifier. Something must be cloning the object because "config" in the tests are referencing a different data structure than the undefined "config" in the modules I want to test.

I'm not sure how to proceed. Maybe re-writing my config module to export a function getConfig() that returns a local config object, and call this function to get the object instead of directly exporting the object itself.

**Comment by speedskater** [comment]
Could you post the code of one of the modules where the config is undefined?

**Comment by PerlPong** [comment]
I have reduced it down to a minimal source tree that demonstrates the issue:

https://github.com/PerlPong/babel-plugin-rewire-issue29

````
src/
├── lib
│   ├── config.js
│   └── some_module.js
├── test
│   ├── helpers
│   │   └── mocha_root_hooks.js
│   └── test.js
└── tests.webpack.js
````

I am not sure if this is an issue with babel-plugin-rewire, or not. But removing babel-plugin-rewire from karma.conf.js makes the test succeed.

**Comment by speedskater** [comment]
Thanks for creating the example. I will have a look into fixing the bug ASAP. But I think I won't be able to work on it before thurdsday.

**Comment by PerlPong** [comment]
No problem, please take your time. I have a potential workaround, which is to not export an object from my config module and manipulate it directly, but instead to export methods getconfig() and setConfig(). But I hate running away from strange bugs like this without fully understanding them. There is so much magic going on, with babel and webpack, etc, that debugging is difficult.

**Comment by speedskater** [comment]
I found the bug.
Please update karma to 0.13.3 see https://github.com/webpack/karma-webpack/issues/65
Second you had a cyclic reference between lib/config and lib/some_module

https://github.com/speedskater/babel-plugin-rewire-issue29/commit/50d6c1e4a975ab906c2e40d154f378b1a953bf37

**Comment by speedskater** [comment]
@PerlPong does this fix the bug for you?

**Comment by PerlPong** [comment]
Thanks for looking into this. The test case now passes.

I think the cyclic reference is the main issue. It worked fine without the plugin, but it seems like a bad idea anyway, so I will try and re-work my code.

**Comment by TheSavior** [comment]
This plugin should support cyclic includes since that is valid javascript and the module loaders handle it.
