### ISSUE TITLE
[Question] Does not work with ES6 import

### ISSUE THREAD

**Issue by DLMR** [speedskater/babel-plugin-rewire#30]
This modified code from the README.md does not work. Only the import of Path has changed.
```javascript
//var Path = require('path');
import Path from 'path';

var env = 'production';

module.exports = function(name) {
	return Path.normalise(name);
}
```
```javascript
var Normaliser = require('Normaliser');

Normaliser.__Rewire__('Path', {
  normalise: (name) => name;
});

Normaliser.__Rewire__('env', 'testing');
....

Normaliser.__ResetDependency__('Path');
```

Is this a known limitation?

**Comment by speedskater** [comment]
Currently this is a known limitation either use es6 modules import and export or use commonjs require and module exports. is it possible for you to adapt your code?

**Comment by DLMR** [comment]
What do you mean with:
> use es6 modules import and export 

You mean that you can't mix them, because that is what I need to do now.

Currently I have adapted my code for it to work. It looks like this:
```javascript
const Path = require('path');

exports default function Normaliser(name) {
	return Path.normalise(name);
}
```

```javascript
import Normaliser, {__Rewire__} from 'Normaliser';

__Rewire__('Path', {
  normalise: (name) => name;
});
....
```

This works but I would rather have `import Path from 'path'` but as I understand it from you this is not possible today. I have understood this correctly?

**Comment by speedskater** [comment]
I have already staged a fix for your problem, but it will take till tomorrow till a new version of babel plugin rewire is available.

**Comment by DLMR** [comment]
Awesome! No stress, thanks for the quick reply.

Will keep this issue open and test when a new version have been published.

**Comment by speedskater** [comment]
I think the problem should be fixed in 0.1.14. Please let me know if the fix works for you.

**Comment by DLMR** [comment]
Unfortunately this is not yet fixed in 0.1.14.

**Comment by speedskater** [comment]
@DLMR Could you please add a PR with a sample code? (sample code in corresponding directory below samples and add a reference to this directory to BabelRewirePluginUsageTest)

**Comment by DLMR** [comment]
Will do that and get back to you.

**Comment by speedskater** [comment]
Perfect thanks.

**Comment by DLMR** [comment]
This problem seems to be related to when using `isparta-loader` together with this plugin. Without `isparta-loader` this example works fine in the latest version.

**Comment by TheSavior** [comment]
It would be great to figure out what is happening that causes these incompatibilities with other libraries. Ideally babel-plugin-rewire should be totally transparent to everything else.

**Comment by speedskater** [comment]
@TheSavior I agree. Having a set of samples which can reproduce such kind of errors might be a step in the right direction to solve issues like this.
