### ISSUE TITLE
Error with babel loader: Cannot modify non-writable property '__get__'

### ISSUE THREAD

**Issue by malonecj** [speedskater/babel-plugin-rewire#36]
Hi

I'm trying to run tests using karma and the latest version of babel-loader 5.3.2 fails with the following error.

```Cannot modify non-writable property '__get__'```

This issue does not occur with babel-loader 5.3.0

**Comment by speedskater** [comment]
Thanks for reporting. Could you please create a minimum example which reproduces this error?

**Comment by speedskater** [comment]
Is this still and issue with the latest version 0.1.21 ?

**Comment by malonecj** [comment]
it appears to be. I will try and get an example to reproduce this error

**Comment by speedskater** [comment]
Thanks that would be perfect.

**Comment by speedskater** [comment]
Imho this should be fixed by now. Therefore I will close this issue. @malonecj if it is still an issue please reopen it.
