### ISSUE TITLE
Shouldn't modify line numbers

### ISSUE THREAD

**Issue by TheSavior** [speedskater/babel-plugin-rewire#38]
The transform injects new code in many places which changes the line numbers of the original file making it hard to debug. If we could inject all of the necessary code at the end of the file it would be much easier to handle.

**Comment by speedskater** [comment]
Although theoretically a good idea I would highly vote against it. Some parts might be moved to the end but definitively not all. I think it might cause problems because of scoping, execution order TDZ and many more. Maybe is there another way of propagating the original line numbers?

**Comment by TheSavior** [comment]
I think Babel's sourcemaps make this moot. I won't get to testing this theory out for a while so I'll close this and we can reopen if it isn't the case.
