### ISSUE TITLE
Error after calling __Rewire__ with webpack

### ISSUE THREAD

**Issue by Janekk** [speedskater/babel-plugin-rewire#40]
I'm getting such error once I call `__Rewire__()` on a module in my test code:

`TypeError: 'undefined' is not a function (evaluating '__$Setters__[name](value)')`

Did you happen to see this error before? (I can set up a sample repo to reproduce that)

**Comment by speedskater** [comment]
Thanks for reporting the issue. If you could create a PR with a sample reproducing this error this would be perfect (https://github.com/speedskater/babel-plugin-rewire/tree/master/samples + an entry in https://github.com/speedskater/babel-plugin-rewire/blob/master/usage-tests/BabelRewirePluginUsageTest.js)

**Comment by Janekk** [comment]
oh sorry, this turned out to be my mistake. I'll close this one for now. Thanks!

**Comment by scott2449** [comment]
@Janekk can you please elaborate on how you solved this issue? We have the same. I assume it's some config/usage issue but tried lots of variants with no luck.

**Comment by hellosmithy** [comment]
![wisdom_of_the_ancients](https://cloud.githubusercontent.com/assets/866604/11244666/a72171a4-8e06-11e5-9f34-44789a8372f3.png)
