### ISSUE TITLE
Usage with mocha + babel

### ISSUE THREAD

**Issue by nordisk** [speedskater/babel-plugin-rewire#42]
Hi. 
In my `mocha.opts`I use `--compilers js:babel/register` so that I can write my tests in ES6.
Can you provide me a hint on how to use this with Mocha + Babel?

**Comment by speedskater** [comment]
I havn't used it in this way myself. But I think you can use a babel require hook: https://babeljs.io/docs/usage/require/. In the options of the hook you can than specify babel-plugin-rewire. This hook than can be invoked by the --require option of mocha (https://mochajs.org/).
I hope this works for you. Just let me know if this solves your issue?

**Comment by nordisk** [comment]
Hi @speedskater. I just use a custom `.babelrc` with `plugins:["babel-plugin-rewire"]`.
In my `mocha.opts` I just tell mocha to use babel/register, et voila.
Thanks for the awesome plugin!

**Comment by speedskater** [comment]
@nordisk Thanks. Glad to read, that it works for you and you like it.

**Comment by nschurmann** [comment]
This actually throws an error for me, undefined is not a function, on line 26 of babel-plugin-rewire. Seems that `Plugin` is undefined.

**Comment by liusy182** [comment]
I am also hitting the same error when trying to declare the plug-in in `.babel.rc`. I am interested to know how to get it running.

**Comment by ParAnton** [comment]
To make it work I have in my .babelrc file
` "env": {
    "test":{
        "plugins": ["babel-plugin-rewire"]
    }
  }`
and when I run my test I have to tell babel to use the test by setting
`BABEL_ENV=test` in my npm cmd before the mocha command
