### ISSUE TITLE
Cannot rewire instance methods

### ISSUE THREAD

**Issue by valermor** [speedskater/babel-plugin-rewire#45]
Rewiring static methods works ok. I am getting an issue when trying to rewire instance methods.

Example:

module _aclass.es6_:
```javascript
import { BClass } from './bclass.es6';
class AClass {
    constructor() {
        this.bValue = BClass.aStaticMethod();
    }
    getBValue() {
        return this.bValue;
    }
    getBName() {
        return new BClass().getName();
    }
}
export { AClass };
```

module _bclass.es6_:
```javascript
class BClass {
    constructor() {
        this.name = 'B';
    }
    getName() {
        return this.name;
    }
    static aStaticMethod() {
        return 'static';
    }
}
export { BClass };
```

and the tests:
```javascript
import { AClass, __Rewire__ } from './aclass.es6';
describe('Test for rewiring dependencies of a class', function() {
    __Rewire__('BClass', {
        aStaticMethod: () => 'rewired static',
        getName: () => 'rewired getName'
    });
    it('should rewire a static method', function() {
        let theClass = new AClass();

        theClass.getBValue().should.equal('rewired static');
    });
    it('should rewire an instance method', function() {
        let theClass = new AClass();
        theClass.getBName().should.equal('rewired getName');
    })
});
```

  Test for rewiring dependencies of a class
    ✓ should rewire a static method
    1) should rewire an instance method

  1) Test for rewiring dependencies of a class should rewire an instance method:
     TypeError: object is not a function
      at AClass.getBName (test/aclass.es6:14:16)
      at Context.<anonymous> (test/rewire-dependent-class.es6:21:18)

Is this case supported at all?

**Comment by speedskater** [comment]
Hi. Thanks for creating this issue. I think this should be supported. Can you create a PR with a sample containing your example. I will than have a look at it on thursday or friday.

**Comment by TheSavior** [comment]
I don't think it really makes sense to rewire instance methods and I don't believe `rewire` does that either.

**Comment by valermor** [comment]
I am working on a project where supporting instance methods would be a great help.
@TheSavior can you elaborate why this case would not make sense beside whether being supported by `rewire`?

**Comment by TheSavior** [comment]
You don't need rewire for this, you can just get the reference to your Class in your test and overwrite the function on the prototype. The value of rewire (and its family of packages) is to modify private state in modules that you would be otherwise unable to access. 

Rewire should be the base package that simply enables private state and then lets other packages be built on top of it. That is why it is also important to not have this package diverge in any meaningful way from the standard rewire. Packages built on top of rewire should work with rewire, rewireify, rewire-global, and babel-plugin-rewire with no differences.

**Comment by speedskater** [comment]
@TheSavior I totally agree.

@valermor Therefore if you have a case where it is not possible to rewire the class itself it is an issue for babel-plugin-rewire.

**Comment by speedskater** [comment]
@valermor  Did rewireing the class ifself help you?

**Comment by valermor** [comment]
Not really. The approach proposed by @TheSavior requires to have the class under test to expose its dependency in the API. I am not totally in favour of this.
I understand you do not want to alter the primary purpose of the module. However, it seems as if my case would be another use case which won't change the nature of the module but add a useful behaviour to it.
If there is an agreement that this needs to be dropped we can close the issue NP.
Otherwise, I can create a PR with the test. 
Cheers.

**Comment by TheSavior** [comment]
It seems like your use case is what sinon stubs are for. You could set a stub in your beforeEach, right?

**Comment by speedskater** [comment]
@valermor but changing the prototype of a member function should be possible (either directly or by creating a spy)? 

Maybe a project building on top of rewire, babel-plugin-rewire or similar rewire libraries would be a solution to provide convencience functions for this. e.g. rewireClass(module, 'classname', { .... }). 
This utilitiy/helper library could be combined with reset functionality which is than called in an afterEach function. So keeping the functionality of the plugin as simple as possible and providing additional functionality through a plugin? This should work together with my suggestion in this issue https://github.com/speedskater/babel-plugin-rewire/issues/26#issuecomment-127691420.
Could this be a solution?
