### ISSUE TITLE
Comment generated methods so that istanbul coverage will ignore them

### ISSUE THREAD

**Issue by sazzer** [speedskater/babel-plugin-rewire#51]
This plugin by necessity adds a bunch of method declarations to the output file. If you then run unit tests with code coverage, the fact that these generated methods aren't tested means that coverage levels are not reported correctly.

Istanbul supports adding comments to the code to indicate that the next entry is ignored, which will cause coverage levels to be better reported.

What's needed to support this is to add the comment:
```
/* istanbul ignore next */
```
immediately before the appropriate method declarations. This would be the declarations of:

* __GetDependency__
* __ResetDependency__
* __Rewire__
* __RewireAPI__
* __$Getters__ assignments
* __$Setters__ assignments
* __$Resetters__ assignments

**Comment by speedskater** [comment]
@sazzer Thanks for reporting this issue and thanks for the effort you put into creating the PR. As discussed in the PR I think it is maybe not the best solution to put lots of comments into the generated code if it is possible to use alternatives. 
Would isparta be okay for you?
