### ISSUE TITLE
The function under test refers to the original, not the rewired, function

### ISSUE THREAD

**Issue by volkanunsal** [speedskater/babel-plugin-rewire#56]
Given the following, I notice that the functions in the tested file refer to the original, unwired functions.

```javascript
// file.js
import { setupAjaxForm } from 'utils/APIUtils';
...
componentDidMount() {
   setupAjaxForm('form'); // <-- this refers to _setupAjaxFormOrig()
}

// file-test.js
import APIUtils from 'utils/APIUtils';
APIUtils.__Rewire__('setupAjaxForm', jasmine.createSpy('setupAjaxForm'));

describe('#componentDidMount', function() {
  it('should call setupAjaxForm', () => {
      let {setupAjaxForm} = require('utils/APIUtils'); // <-- This refers to setupAjaxForm()
      expect(setupAjaxForm).toHaveBeenCalled();
  });
});
```

The result is tests fail since the spy function is never called.

The only way I managed to have them refer to the rewired copy of the function was by requiring them again inside componentDidMount, but that's not a tenable solution, in my view.

**Comment by speedskater** [comment]
Thanks for reporting the issue. From my point of view it should work. I will try to reproduce the error and fix it.

**Comment by speedskater** [comment]
@volkanunsal I just checked the samples code and we have a sample which does exactly what you are looking for: https://github.com/speedskater/babel-plugin-rewire/tree/master/samples/issue19

Maybe I am missing something but in your sample the componentDidMount method is never called.

**Comment by volkanunsal** [comment]
That's very helpful. I'm sure componenDidMount is being called. I put a `console.log` in that function and saw the output and checked the other day. But I'm not using `__GetDependency__ ` in my test code. Could that be the problem here? I will try using that when I get back to work.

**Comment by volkanunsal** [comment]
I just checked. It's definitely working if the function is accessed this way:

```javascript
import * as APIUtils from 'utils/APIUtils';
componentDidMount() {
   APIUtils.setupAjax('form');
}
```

But not if the function was destructured as the module is imported, as in:


```javascript
import {setupAjax} from 'utils/APIUtils';
componentDidMount() {
   setupAjax('form');
}
```

Any thoughts?

**Comment by TheSavior** [comment]
If you call `module.function` you are calling the function on the module.

If you say
```
var func = module.function;
```

Now `func` points to the same thing that `module.function`. Rewire changes the reference that `module.function` points to. 

In your example that destructures, you are creating `func` like we have above, and that will continue pointing to the original function even after it is rewired. It also changes the reference of `this` inside of the function.

We typically avoid importing raw functions from objects for this reason.

**Comment by volkanunsal** [comment]
Is there any way around this? Function import is a pretty common convention and can translate to significant saving in file size after dead code elimination has run. By importing the entire module, we'd be losing all that benefit.

**Comment by TheSavior** [comment]
We typically use [`proxyquire`](https://github.com/thlorenz/proxyquire) to change the functionality of dependencies instead of rewire.

**Comment by volkanunsal** [comment]
I'll check it out. Looks promising. I assume it can get around the problem with function import?

**Comment by speedskater** [comment]
@volkanunsal @TheSavior  imho in an es6 context the rewirering of named imports should definitively work. @volkanunsal could you please generate a PR with a sample which reproduces your error. I will have a look at it and will try to fix it.

**Comment by speedskater** [comment]
@volkanunsal Is this still an issue for you??? (0.1.23-beta-3)

**Comment by volkanunsal** [comment]
@speedskater Hey! Sorry,  I didn't see your post before the last one. I will take a look. How can I install 0.1.23-beta-3? It's not on npm or in this repo.

**Comment by speedskater** [comment]
@volkanunsal Hi, never mind. It is a beta version therefore it is not listed in the repository. But you can just enter the version in your package.json and it should install.

**Comment by volkanunsal** [comment]
It works!

**Comment by speedskater** [comment]
@volkanunsal  Thanks for checking
