### ISSUE TITLE
Problem with default export of default import from module

### ISSUE THREAD

**Issue by kamilio** [speedskater/babel-plugin-rewire#58]
I've noticed strange behaviour when using this export/import construct. It does not expose the original module, just object with the rewrite enhancement methods.

```es6
export { default } from './components/Table';
```

```es6
{ __GetDependency__: [Function: __GetDependency__],
  __get__: [Function: __GetDependency__],
  __Rewire__: [Function: __Rewire__],
  __set__: [Function: __Rewire__],
  __ResetDependency__: [Function: __ResetDependency__] }
```

You can find failing test for such a scenario in following commit https://github.com/kamilio/babel-plugin-rewire/commit/2b3b0fcac62b2a28acbef33567be1ec1f74a4778

Thanks a lot

**Comment by speedskater** [comment]
Thanks for reporting the issue and the samples. I created a fix. It will be contained in the upcoming beta version.
