### ISSUE TITLE
mutual imports

### ISSUE THREAD

**Issue by baabgai** [speedskater/babel-plugin-rewire#59]
I stumbled over a issue with mutual imports.
Within my code base I have situation like this:

mod1.js
```javascript
import { SUCCESS, FAILURE } from '.mod2';
import { fun3 } from './mod3';
function start() {
  let res = fun3(SUCCESS);
  console.log(res);
  let res = fun3(FAILURE);
  console.log(res);
}
start();
```

mod2.js
```javascript
import { STATUS } from './mod3';
export const SUCCESS = 'SUCCESS';
export const FAILURE = 'FAILURE';
function porcStatus() {
  return STATUS;
}
```

mod3.js
```javascript
import { SUCCESS, FAILURE } from './mod2';
export const STATUS = 'OK';
export function fun3(signal) {
  switch (signal) {
  case SUCCESS:
    return 'positive';
  case FAILURE:
    return 'negative';
  default:
    return 'uups';
}
```

Processing these file with babel alone works fine the output is as expected
```bash
positive
negative
```

running the files with ```babel --plugins rewire``` leads to the output
```
uups
uups
```

When running with rewire, at the stage of running the switch statement in ```fun3``` the imported constants ```SUCCESS``` and ```FAILURE``` appear to be undefined.

I guess that is not really expected behavior or would there be some work around for this problem?

**Comment by michaelcontento** [comment]
Some problem here :(

**Comment by speedskater** [comment]
@baabgai, @michaelcontento The problem is caused by dynamic binding of imports. I have created a fix which should support mutual imports. As this resulted in a huge change I will create a beta version over the next hours. If this beta version works for you and all other babel-plugin-rewire users I will switch to a stable number again.

**Comment by speedskater** [comment]
@baabgai @michaelcontento new version 0.1.23-beta-3 is online this should fix your issues. Please let me know if it works for you.

**Comment by baabgai** [comment]
sorry for the late response. The test cases seem to work perfectly fine now and I will try to include it again in the main project to see if everything works as expected outside the simple example above.
