### ISSUE TITLE
Cannot redefine property: __Rewire__

### ISSUE THREAD

**Issue by srph** [speedskater/babel-plugin-rewire#64]
I am using Karma and Webpack to run this plugin.

This seems to occur around these lines:

```js
	if (typeof module.exports === 'object' || typeof module.exports === 'function') {
	  Object.defineProperty(module.exports, '__Rewire__', {
	    'value': __Rewire__,
	    'enumberable': false
	  });
```

This is my webpack loader config:

```js
  module: {
    loaders: [
      {
        test: /\.(js|jsx|es6)$/,
        exclude: '../../node_modules/',
        loader: 'babel-loader?plugins=babel-plugin-rewire&modules=common&stage=0'
      }
    ]
  },
```

Not sure if https://github.com/speedskater/babel-plugin-rewire/issues/57 or https://github.com/speedskater/babel-plugin-rewire/issues/44 is related. Anybody care to check?

**Comment by speedskater** [comment]
@srph It seems that this issue is related to https://github.com/speedskater/babel-plugin-rewire/issues/57
as well as https://github.com/speedskater/babel-plugin-rewire/pull/62. As soon as a new version is available which sould happen within the next hours this should solve your issue.

**Comment by srph** [comment]
Really, really thanks :cupid: . Looking forward to it :smile:

**Comment by speedskater** [comment]
@srph :). Could you please try the beta version 0.1.23-beta-3. And let me know if this fixes the issue for you?

**Comment by srph** [comment]
I got new errors:

```
Uncaught TypeError: Cannot assign to read only property '__GetDependency__' of [object Object]
```

**Comment by speedskater** [comment]
@srph . Thanks for testing. Could you please provide a toy example or a PR with the sample, such that i can reproduce your error and provide a fix.

**Comment by srph** [comment]
I'll try, but I got the error around these lines.

```es6
        exports['default'] = _defaultExport;
	exports.__GetDependency__ = _GetDependency__;
	exports.__get__ = _GetDependency__;
	exports.__Rewire__ = _Rewire__;
	exports.__set__ = _Rewire__;
	exports.__ResetDependency__ = _ResetDependency__;
	exports.__RewireAPI__ = _RewireAPI__;
```

**Comment by dmwyatt** [comment]
I'm hitting the original issue in this thread.  I can try out any beta versions, or if @speedskater can describe the source of the issue in more detail, I might take a shot at a PR to fix the problem...

**Comment by speedskater** [comment]
@dmwyatt did 0.1.23-beta-3 solve your issue? 
@srph is this the generated or is this your code?

**Comment by srph** [comment]
Generated code, and it seems to be from rewire.

**Comment by speedskater** [comment]
@srph thanks for the feedback. I am more interested in the original not in the generated source code. So if you could create a simple toy example which results in the error it would be perfect. This would help me to reproduce the error.

**Comment by srph** [comment]
Noted. Let me work on it. I'll report anything I find.

**Comment by speedskater** [comment]
@srph Thanks :+1:

**Comment by srph** [comment]
I found out something. It'll be a little bit long, so hang on. Like I said, AFAICR, I'm using Webpack and Karma. I forgot to mention that I'm using Sinon and Chai.

This was my webpack config for finding all test files:

```es6
// build/tests/webpack.files.js
/**
 * Setup context module
 * http://webpack.github.io/docs/context.html
 */
var ctx = require.context('../../common/', true, /\.spec\.js$/);
ctx.keys().forEach(ctx);
```

Instead of running all tests, I made a dummy suite:

```es6
// build/tests/dummy.spec.js
describe('test', () => {
  it('should not fail', () => {
    expect(1).to.equal(1);
  });
});
```

And change my webpack config (for resolving spec files):

```js
// build/tests/webpack.files.js
var ctx = require.context('./', true, /\.spec\.js$/);
ctx.keys().forEach(ctx);
```

No hints of error. I am intensively using Sinon, so my first clue (although not concrete), is that we're having issues with Sinon. But I have yet to prove this.

**Comment by srph** [comment]
I'm sending a demo in a few minutes. It seems that I was correct.

**Comment by srph** [comment]
Aha, I think I found out. This makes the error:

```js
export const pogi = 5;
export default exports; // The error triggers whenever I uncomment this line
```

**Comment by dmwyatt** [comment]
@speedskater Yes, 0.1.23-beta-3, does fix the issue for me.

**Comment by speedskater** [comment]
@srph thanks for testing. Could you provide the whole sample file which contains "export default exports;" I would like to analyze if this could be a an error in certain edge cases.

**Comment by srph** [comment]
You can just copy-paste it. My sample is as it is. It bugged with that exact sample :)
