### ISSUE TITLE
Problems when using `react-require`

### ISSUE THREAD

**Issue by djskinner** [speedskater/babel-plugin-rewire#66]
Let's say I have a React component as follows:

```
import React from 'react';

const InfoButton = ({enabled}) => (
    <div className={enabled ? 'enabled' : ''}>Info</div>
);

export default InfoButton;
```

Here I'm using React 0.14's new stateless functional component syntax but the problem applies to any React component.

Despite not explicitly using the `React` import I have to define it or Babel will complain and fail. However this is a bit annoying not least because of the eslint warnings but also because it's unclear to other developer why that seemingly redundant line needs to be there.

So, I discover [`babel-plugin-react-require`](https://github.com/vslinko/babel-plugin-react-require) and now I can remove the problematic `import React from 'react';` line.

However when using this plugin alongside `babel-plugin-rewire` as we do in our tests we get the following error:

```
ERROR in ./InfoButton.jsx
Module build failed: TypeError: ./InfoButton.jsx: Cannot set property 'constant' of undefined
  at ./node_modules/babel-plugin-rewire/src/babel-plugin-rewire.js:242:49
  at Array.forEach (native)
  at NodePath.Plugin.visitor.ImportDeclaration (./node_modules/babel-plugin-rewire/src/babel-plugin-rewire.js:236:21) 
```

**Comment by djskinner** [comment]
If I leave both plugins enabled but put the import declaration back in the error disappears.

**Comment by TheSavior** [comment]
Does the order in which you specify the Babel plugins matter?

**Comment by djskinner** [comment]
Yes, it does. `babel-plugin-rewire` before `react-require` in `.babelrc` solves the problem:

```
      "plugins": [
        "babel-plugin-rewire",
        "react-require"
      ]
```

Many thanks!
