### ISSUE TITLE
Question about how to use this to import an entire file, similar to rewirejs

### ISSUE THREAD

**Issue by amalahussein** [speedskater/babel-plugin-rewire#67]
question is in the title--thanks!

**Comment by speedskater** [comment]
@amalahussein Could you please be a bit more detailed about your question :)

**Comment by TheSavior** [comment]
@amalahussein Can this be closed?

**Comment by amalahussein** [comment]
@TheSavior hey sorry, I havent come back to this issue, but my question was in the case where I have a dependency that I am importing, such as:

example.js/
import {hello} from './hello.js'

export function example(){
return Hello.methodOnHello()
}

I would like to rewire Hello, when testing example.js, is this possible?

**Comment by TheSavior** [comment]
Would [proxyquire](https://github.com/thlorenz/proxyquire) work for this case?

**Comment by amalahussein** [comment]
@TheSavior thats good to know---I know the the non-babel rewire library, I would be able to change Hello into whatever I want... but I won't be able to do this babel-plugin-rewire? If not, is this feature part of the pipeline? 

Thanks, 
Amal

**Comment by speedskater** [comment]
@amalahussein Sorry for the very late reply. As far as I have understood you want to rewire global variables. As you are can change global variables by using simple code like 
```js
Hello.methodOnHello = ....
```
or by using libraries which make this easier for you we have decided that we do not want to rewire global variables. Instead we rewire inter as well as first level intra file dependencies.

Therefore I will close this issue for now. If I have missunderstood you please feel free to reopen this issue.
