### ISSUE TITLE
TypeError: cannot read property 'declarations' of undefined

### ISSUE THREAD

**Issue by baabgai** [speedskater/babel-plugin-rewire#69]
When exporting undefined variables, stand-alone ```babel <filename>.js``` transpiles the following just fine 
```
export var status;
```
is translated to
```
'use strict';
Object.defineProperty(exports, "__esModule", {
  value: true
});
var status;
exports.status = status;
```
running the same snippet together with ```babel --plugins rewire <filename>.js``` leads to an error message
```
TypeError: <filename.js>: Cannot read property 'declarations' of undefined
at ..../babel-plugin-rewire.js:210:49
....
```

Just to give some context why somebody would export a undefined variable (it's actually not my choice). We work on a Typescript project and Typescript offers the possibility for defining enums like
```
export enum Status = { LOADING, SUCCESS, FAILURE }
```
this get's compiled from the typescript compiler into
```
export var Status;
(function (Status) {
  Status[Status["LOADING"] = 0] = "LOADING";
  Status[Status["SUCCESS"] = 1] = "SUCCESS";
  Status[Status["FAILURE"] = 2] = "FAILURE"; 
})(Status || (Status = {}));
;
```
trying to run that code through babel with rewire plugins leads to the error described above.

**Comment by speedskater** [comment]
@baabgai I think I have fixed your issue and provided a new beta version 1.0.0-beta-2. Could you please test it and if you have any issues with it could you please provide a PR with a minimal sample reproducing your error (analog to the samples in the repo used by https://github.com/speedskater/babel-plugin-rewire/blob/master/usage-tests/BabelRewirePluginUsageTest.js.)

**Comment by baabgai** [comment]
Integrated the new beta in to our project and everything seems to work fine now.
Thanks for the fix!
