### ISSUE TITLE
How to work with `babel-plugin-add-module-exports`

### ISSUE THREAD

**Issue by dtothefp** [speedskater/babel-plugin-rewire#80]
I'm having a painful experience updating to Babel 6. Part of this is because Babel seems to have deprecated behavior

```js
//some.js
export default {
  stuff: 'things'
}

//importer.js
import {stuff} from './some.js';

console.log(stuff); //undefined
```

I was happy to find https://github.com/59naga/babel-plugin-add-module-exports but unfortunately when used in combination with `rewire` the `undefined` behavior returns. I'm trying to avoid having to go through my entire app and replace all instances of where I'm exporting/importing in this manner. Is there a way to get these two plugins working together?

```
{
  "presets": ["react", "es2015", "stage-0"],
  "plugins": ["add-module-exports", "rewire"]
}
```
or

```
{
  "presets": ["react", "es2015", "stage-0"],
  "plugins": ["rewire", "add-module-exports"]
}
```

**Comment by speedskater** [comment]
@dtothefp I haven't considered this till yet. I will have a look at it on monday, but i cannot guarantee that I will be able to fix you issue (highest priority is to keep in line with the babel 6 behavior and the es6 standard).
.

**Comment by speedskater** [comment]
@dtothefp. Sorry but I will close this issue for now and will not add any special behaviour for handling common.js default export. 

Imho if your goal is to switch to prure es2015 you will eventually have to bite the bullet and switch your legacy code anyway. The reason why this plugin will not work is, that it adds further exports which will be lost in case of rewriting the default export.
Moreover even if we could detect that only one default export exists its very hard or even impossible to guess the intended usage by the importer.

Maybe you could automate the task of updating your exports/import by creating a code mod (https://medium.com/@cpojer/effective-javascript-codemods-5a6686bb46fb#.ia2q4af37) which executes the tedious task for you. 
I think this could be very helpful for other developers as well (which face the same task). 

Could this work for you?

**Comment by dtothefp** [comment]
@speedskater no problem, we manually fixed these issues a while back. Was a painful process but all is good now. Just thought it might be interesting to try and specify how Babel plugins work together. It seems this is often an issue for people, that they add a plugin and it doesn't play nice with another plugin.

**Comment by andrewmunro** [comment]
@dtothefp What was your fix for this? I've just upgraded to Babel 6 and having the same problem :(

**Comment by dtothefp** [comment]
@andrewmunro no fix I bit the bullet. If you have a big application you might Google around for a tool that might automate the process of changing your `export default` to `export const`. The biggest pin for us was also tracking down where this was happening in our private sub modules that we were consuming uncompiled

**Comment by andrewmunro** [comment]
If that's the case I think I'd rather use an alternative like https://www.npmjs.com/package/inject-loader. Rewire has been causing us headaches for months...

**Comment by speedskater** [comment]
@andrewmunro I know this is annoying, but I think tackling the problem, maybe with a tool like jscodeshift or similar will be more futureproof and should be doable. 

The reason is that the previous behavior is not es2015 compliant and may or may not break anytime if you you use another module loader.

If you tackle this problem with jscodeshift could you provide the codemod for other users, which face a similar problem?

**Comment by andrewmunro** [comment]
@speedskater I understand the problem and I appreciate all the work you've done supporting this plugin, but personally I think it introduces more problems than it solves.

Enforcing rewire on all requires/imports in tests not only adds on a significant amount of processing time for us (adds around 10s to the babel transpilation process), but I constantly have problems with tests leaking as developers forget to use `__ResetDependency__`. I much prefer the original rewire pattern of explicitly wrapping your objects with rewire within the tests.

I also think that using a codemod is over-engineering what should be a relatively simple task. Sorry, I don't want to turn this issue into a huge conversation and get off topic, but over the last few days searching I found relatively little information on the subject of mocking out modular dependencies.

**Comment by mmahalwy** [comment]
@andrewmunro what have you done then?

**Comment by andrewmunro** [comment]
@mmahalwy see:

https://github.com/speedskater/babel-plugin-rewire/issues/80#issuecomment-214556405

I'm now using inject-loader and finding test performance much better.

Changes:

```
import XhrHandler from 'path/to/XhrHandler'
...
mockModule = sinon.spy();
XhrHandler.__set__('XMLHttpRequest', mockModule);
```

to

```
mockModule = sinon.spy();
let XhrHandler = require('inject!path/to/XhrHandler')({
    'path/to/Module': mockModule
})
```

You have an added bonus that you don't have to worry about calling `__ResetDependency__` since the injectloader only injects modules within the scope of your test, not globally. I find this much cleaner and more explicit than rewiring every single module via a babel plugin.
