### ISSUE TITLE
Cannot get hold of private function in module

### ISSUE THREAD

**Issue by nordisk** [speedskater/babel-plugin-rewire#83]
Hi. We are trying to get hold of a private/internal function from a module with Rewire so that we can test that function without changing the implementation not its api in the test.js.

Here we are trying to get hold of `privateFunc` from `test.js` in `test.spec.js`. We cannot get hold of it.

```js
// test.js
export default function Test() {

	function privateFunc(str) {
		// Do some private fancy stuff here
		return str;
	}

	function publicFunc(str) {
		// Use privateFunc here to do some stuff
		return privateFunc(str);
	}

	//Test API
	return {
		aFunc(str) {
			return publicFunc(str);
		}
	}
}

// test.spec.js
import {default as Test, __RewireAPI__ as TestAPI} from "./test";
const TestInstance = Test();


// Get hold of private function from test.js
let privateFunc = TestAPI.__get__("privateFunc"); // yields undefined
```

Any clues? Cheers.
/cc @aarong11 @mark-berry-localstars

**Comment by TheSavior** [comment]
It should work if you move privateFunc to the top level scope.

**Comment by nordisk** [comment]
Thanks @TheSavior It worked. But putting `privateFunc` outside of the closure of Test() will make it global I guess.

**Comment by TheSavior** [comment]
Global? It is only accessible inside of the file.

**Comment by nordisk** [comment]
@TheSavior That is true for native ES6 modules/CommonJS environments. I guess transpiled code will have to use Browserify/WebPack in a browser context that would wrap the CommonJS export in a closure and expose only the exports.

```js
"use strict";

exports.__esModule = true;
exports["default"] = Test;
function privateFunc(str) {
    // Do some private fancy stuff here
    return str;
}

function Test() {
    function publicFunc(str) {
        // Use privateFunc here to do some stuff
        return privateFunc(str);
    }

    //Test API
    return {
        aFunc: function aFunc(str) {
            return publicFunc(str);
        }
    };
}

module.exports = exports["default"];
```

Anyways, closing this down as the top-level tip seems to work. Thanks @TheSavior.
