### ISSUE TITLE
Rewire Flux stores which are singletons

### ISSUE THREAD

**Issue by kbiedrzycki** [speedskater/babel-plugin-rewire#85]
I am looking for solution how to use rewire babel plugin with Flux stores, which are basically singletons. According to this article http://bensmithett.com/testing-flux-stores-without-jest/ each rewire() call returns fresh singleton instance, but not sure how can I acheive same effect using babel plugin (or is it even possible?). I am also usign webpack configuration for that, as far as I saw I have access to whole Rewire API inside Flux Store, but I couldn't reset stores' state. Any thoughts on that?

**Comment by speedskater** [comment]
@kbiedrzycki sorry for the late answer. Regarding your request using this plugin you are not able to retrieve a fresh singleton, but you can rewire all local variables and all imports used inside of the module where the singleton is located. Maybe this will allow you to achieve your required behavior. 
Another approach is to use an architecture like redux where stores are simple reducer function which itself store no state and hence are very easy to test. 
Please let me know if this answer is sattisfying for you.

**Comment by TheSavior** [comment]
@kbiedrzycki It might make sense to use something meant for that like:
https://github.com/nazomikan/require-without-cache
https://github.com/yuri0/require-nocache
https://github.com/hughsk/fresh-require

**Comment by speedskater** [comment]
@kbiedrzycki. Sorry that i couldn't help more but I will close this issue.
