### ISSUE TITLE
Duplicate declaration "typeOfOriginalExport"

### ISSUE THREAD

**Issue by jakemmarsh** [speedskater/babel-plugin-rewire#87]
Seeing the error `Duplicate declaration "typeOfOriginalExport" (This is an error on an internal node. Probably an internal error)` when using proxyquire. Looks to be covered in #84

**Comment by speedskater** [comment]
@jakemmarsh The testcase of #84 is covered in the current code base. Now its up to proxyquire to work correctly with babel plugin rewire.

**Comment by jonashartwig** [comment]
Hi, I get this error too but I am not using proxyquire.

modules:


  "devDependencies": {
    "babel-core": "^6.5.1",
    "babel-loader": "^6.2.3",
    "babel-plugin-rewire": "^1.0.0-beta-5",
    "babel-polyfill": "^6.5.0",
    "babel-preset-es2015": "^6.5.0",
    "babel-preset-react": "^6.5.0",
    "babel-preset-stage-0": "^6.5.0",
    "chai": "^3.5.0",
    "chai-things": "^0.2.0",
    "copyfiles": "^0.2.1",
    "css-loader": "^0.23.1",
    "cssnano": "^3.4.0",
    "enzyme": "^1.4.1",
    "extract-text-webpack-plugin": "^1.0.1",
    "filesaver.js": "0.2.0",
    "fixed-data-table": "^0.6.0",
    "immutable": "^3.7.6",
    "json-loader": "^0.5.4",
    "jszip": "2.5.0",
    "karma": "^0.13.21",
    "karma-babel-preprocessor": "^6.0.1",
    "karma-chai": "^0.1.0",
    "karma-chai-things": "^0.1.4",
    "karma-chrome-launcher": "^0.2.2",
    "karma-coverage": "^0.5.3",
    "karma-es6-shim": "^0.2.3",
    "karma-html2js-preprocessor": "^0.1.0",
    "karma-junit-reporter": "^0.3.8",
    "karma-mocha": "^0.2.2",
    "karma-mocha-reporter": "^1.1.5",
    "karma-phantomjs-launcher": "^1.0.0",
    "karma-phantomjs-shim": "^1.2.0",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-sinon": "^1.0.4",
    "karma-sinon-chai": "^1.1.0",
    "karma-webpack": "^1.7.0",
    "mocha": "^2.4.5",
    "moment": "2.11.1",
    "moment-timezone": "0.5.0",
    "mousetrap": "^1.5.3",
    "node-hook": "^0.2.0",
    "node-sass": "^3.4.2",
    "on-build-webpack": "^0.1.0",
    "phantomjs-prebuilt": "^2.1.2",
    "postcss-loader": "^0.8.0",
    "react-addons-test-utils": "^0.14.6",
    "react-pure-render": "^1.0.2",
    "react-redux": "^4.1.2",
    "redux": "^3.1.7",
    "redux-thunk": "^1.0.3",
    "reselect": "^2.0.2",
    "sass-loader": "^3.1.2",
    "sinon": "^1.17.3",
    "sinon-chai": "^2.8.0",
    "source-map-loader": "^0.1.5",
    "style-loader": "^0.13.0",
    "webpack": "^1.12.13"
  }

karma conf:

var webpack = require("webpack");

module.exports = function (config) {
    config.set({
        basePath: "../../",
        frameworks: [
            "mocha",
            "sinon-chai",
            "chai-things",
            "chai",
            "es6-shim"
        ],
        plugins: [
            "karma-chrome-launcher",
            "karma-webpack",
            "karma-junit-reporter",
            "karma-coverage",
            "karma-mocha",
            "karma-mocha-reporter",
            "karma-sinon",
            "karma-sinon-chai",
            "karma-chai",
            "karma-chai-things",
            "karma-es6-shim"
        ],
        files: [
            "https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js",
            "http://kendo.cdn.telerik.com/2015.3.930/js/kendo.all.min.js",
            "react/test/**/*.spec.js"
        ],
        exclude: [],
        preprocessors: {
            "react/src/**/*.js": ["webpack"],
            "react/test/**/*.spec.js": ["webpack"]
        },
        reporters: ["progress", "mocha", "coverage", "junit"],
        webpack: {
            devtool: "inline-source-map",
            module: {
                loaders: [
                    {
                        test: /\.jsx?$/,
                        loader: "babel-loader",
                        exclude: /node_modules/,
                        query: {
                            presets: ["es2015", "stage-0", "react"],
                            plugins: ["babel-plugin-rewire"]
                        }
                    },
                    {
                        test: /\.s?css$/,
                        exclude: /node_modules/,
                        loaders: ["style", "css", "sass"]
                    },
                    {
                        include: /\.json$/,
                        loaders: ["json-loader"]
                    }
                ]
            },
            resolve: {
                extensions: ["", ".js", ".jsx", ".scss", ".css", ".json"]
            },
            externals: {
            },
            node: {
                fs: "empty"
            },
            plugins: [
                new webpack.DefinePlugin({
                    RTC_SERVICE_URL: JSON.stringify('/'),
                    ADMIN_SERVICE_URL: JSON.stringify('/'),
                    APP_SERVICE_URL: JSON.stringify('/'),
                    BATCH_WEB_URL: JSON.stringify('/'),
                    BATCH_SERVICE_URL: JSON.stringify('/'),
                    SERVICE_URL: JSON.stringify('/'),
                    GPEH_WEB_URL: JSON.stringify('/'),
                    GRAPH_SERVICE_URL: JSON.stringify('/'),
                    ARCHIVE_SERVICE_URL: JSON.stringify('/')
                })
            ]
        },
        webpackServer: {
            noInfo: true
        },
        webpackMiddleware: {
            noInfo: true
        },
        stats: {
            children: false
        },

        port: 9875,
        colors: true,
        logLevel: config.LOG_INFO,
        autoWatch: true,
        browsers: ["Chrome"],
        singleRun: false,
        browserDisconnectTimeout: 30000,
        junitReporter: {
            outputFile: "target/reports/junit/TESTS-xunit-flux.xml"
        },
        client: {
            mocha: {
                timeout: "15000"
            }
        }
    });
};

**Comment by erykpiast** [comment]
Use "````javascript" ;)

**Comment by TheSavior** [comment]
This is still a problem for us using 1.0.0 rc1

**Comment by TheSavior** [comment]
I think I finally tracked it down. I'll see if I can make a failing test.

**Comment by TheSavior** [comment]
New ticket with a failing example at #106

**Comment by paothegit** [comment]
I also have this error on version 1.0.0-rc-1
