### ISSUE TITLE
Webpack + Karma

### ISSUE THREAD

**Issue by kristian-puccio** [speedskater/babel-plugin-rewire#91]
Hi,

I'm trying use this with Karma + Webpack and get the following error:
```
PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
  RangeError: Invalid array length
```

The relevant config is:
```
				module: {
					loaders: [
						{
							test: /\.jsx?$/,
							exclude: /node_modules/,
							loader: 'babel',
							query: {
								stage: 0,
								optional: ['runtime'],
								plugins: ['babel-plugin-rewire'],
							},
						},
						{ test: /\.json$/, loader: 'json' },
					],
```

When I remove the plugins line in the query the error goes away. I'm using babel 5.
Not sure how to give you more info but I realise this isn't that helpful.

**Comment by karlnp** [comment]
Have you tried removing the trailing comma on the second loader definition?

**Comment by karlnp** [comment]
And on the plugins line, actually.

**Comment by kristian-puccio** [comment]
Pretty sure that isn't it as I use trailing comma's everywhere.
But I have updated to babel 6 and now this works perfectly using beta 5 so I'm going to close this.

Thanks!

**Comment by speedskater** [comment]
@kristian-puccio thanks for your feedback.
