### ISSUE TITLE
Syntax error using switch statement with jsx

### ISSUE THREAD

**Issue by zh3** [speedskater/babel-plugin-rewire#92]
When using `babel-plugin-rewire@1.0.0-beta-5`, `react@0.14.5` and babel 6 the following switch statement containing jsx
```jsx
  switch (type) {
    case 'password':
      fieldComponent = <PasswordFieldComponent {...fieldProps} validateFormField={props.validateFormField} />;
```
Results in an error when transpiling
```
Module build failed: SyntaxError: /utils/form-field-builder.js: Unexpected token (86:4)
  84 | 
  85 |   switch (type) {
> 86 |     var _PasswordFieldComponent_Component = _get__('PasswordFieldComponent');
     |     ^
  87 | 
  88 |     case 'password':
  89 |       fieldComponent = _react2.default.createElement(_PasswordFieldComponent_Component, (0, _extends3.default)({}, fieldProps, { validateFormField: props.validateFormField }));
```

Failing test case by @ahutchings #90

**Comment by TheSavior** [comment]
This is currently the part keeping us from being able to upgrade to babel 6 as well.

**Comment by speedskater** [comment]
@zh3 thanks for the report. @TheSavior I will have a look at it asap but i think it will not be before next 	wednesday.

**Comment by brutcha** [comment]
+1

**Comment by redking** [comment]
I'm encoutering the same problem - I've prepared a simplified test case: 

https://github.com/redking/babel-plugin-rewire-bug

Note that I'm not actually using rewire mocks in the tests themselves - it's enough to include `babel-plugin-rewire` in the list of plugins in `.babelrc` to see the error. Remove it from the list and the error no longer occurs.

**Comment by speedskater** [comment]
@redking thanks for providing the test.

**Comment by redking** [comment]
No problem - I just noticed there's a pending pull request on the same issue, so it's not much use in the end :)

**Comment by zh3** [comment]
Attempted to fix this #103

**Comment by speedskater** [comment]
@zh3 thanks for providing the pr. I will try to merge it before the end of this week.

**Comment by speedskater** [comment]
@zh3 thanks for the fix it is merged. I extended it to work for nested switch statements as well.

**Comment by zh3** [comment]
@speedskater great, thanks for all your work on this plugin!

**Comment by speedskater** [comment]
@zh3 thanks, you are welcome

**Comment by uriklar** [comment]
I'm still experiencing this issue with version 1.0.0-rc-4
